version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=sqlite:///interview_trainer.db
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=gpt-3.5-turbo
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - interview-trainer

  # Optional: Add a database service if needed in the future
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: interview_trainer
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - interview-trainer

networks:
  interview-trainer:
    driver: bridge
# volumes:
#   postgres_data:
